### PR TITLE
update camera optimizer to match nerfstudio

### PR DESCRIPTION
**Pull request by lsongx**
camera optimizer has been move to model in https://github.com/nerfstudio-project/nerfstudio/pull/2092

Currently, it will throw an error if we want to init it in datamanager as before:
```
TypeError: RayGenerator.__init__() takes 2 positional arguments but 3 were given                                        
```

### CODE REVIEW

**Comment by ayaanzhaque** [comment]
Sorry! For some reason I did not see a notification for this PR. Thank you for fixing this!

**Comment by lsongx** [comment]
No worries! I'm happy to help in any way I can.

**Comment by ayaanzhaque** [comment]
@lsongx If you have any time, can you help me figure out why the results with newer diffusers/nerfstudio look bad? I narrowed it down to an issue with how the edited images look, so I assume it is a diffusers issue, but if you can just print out the edited images and take a look, I would greatly appreciate it

**Comment by lsongx** [comment]
Is it https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/60?
I have trouble replicating this issue. Everything looks fine on my side. Maybe we can discuss it under that issue

**Pull request merged**
